[package]
name = "executable"
version = "0.1.0"

[dependencies]
library = { path = "crates/library" }
library_dylib = { path = "crates/library_dylib" }

[profile.dev]
lto = "thin" #true

[workspace]
members = ["crates/*"]